### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by space192** [jeremyfix/dcejs#39]
With the latest release of dce-js 1.9.4 I get the following error when starting the app 😅
<img width="518" alt="Capture d’écran 2023-12-13 à 11 23 18" src="https://github.com/jeremyfix/dcejs/assets/44359684/a55e1d3e-2f1e-4b4b-a692-fb9bf27e1ba2">

**Comment by jeremyfix** [comment]
Thank you for the bug report; 

I suppose, but correct me if I'm wrong, this is happening when :

- you run dcejs on MacOs
- you run a "Start VNC"

If this is correct, I have to check the reason but this bug should only occur on MacOS users for which we use xml2json which is the dependency complaining for the missing node-expat module. 

I have to check why the xml2json module is not installing its dependency ; Otherwise I could also drop the feature we implement with xml2json.

Basically , for Mac users, I'm using this xml2json to look for  the vncviewer so as to provide a direct accessor to the vnc viewer. It is not easy for me to test on MacOS  ; However, I'm wondering if this was working at all for Mac users (that may push the balance toward removing the feature if this is useless);

With the previous working version of dcejs, running VNC, did you notice a clickable blue link on the VNC url ? As on the screenshot below ? That link is expected to be clickable. That was expected at least :) Was it the case ? 

![image](https://github.com/jeremyfix/dcejs/assets/1128418/f96e96bf-7776-4ebe-821c-350a789e26bc)

**Comment by space192** [comment]
no the crash happens the moment I start the application 

https://github.com/jeremyfix/dcejs/assets/44359684/acdacf31-6dd5-4e63-ba5c-01e76f671af2

previous versions were working fine I had the blue link on your screenshot, and xml2json was already installed on my mac

**Comment by jeremyfix** [comment]
Ok, right, this makes sense, this is at import time ; So it makes sense it crashes at startup ; 

I will check If I keep or not this feature on MacOS or if I can identify which the dependency behind xml2json is missing.

**Comment by jeremyfix** [comment]
Indeed there is a build issue on the MacOS platform 

https://github.com/jeremyfix/dcejs/actions/runs/7184760935/job/19566583579#step:4:26

**Comment by jeremyfix** [comment]
However, the upstream package ,xml2json (https://github.com/buglabs/node-xml2json) is deprecated, and itself depends on deprecated packages ; I will certainly drop the feature and publish a new release soon.

**Comment by space192** [comment]
love how the logs says that `info This module is OPTIONAL, you can safely ignore this error` 😅

**Comment by jeremyfix** [comment]
@space192  would you mind giving a try to this release ? https://github.com/jeremyfix/dcejs/releases/tag/v1.9.5

It is expected to run with the removal of the "blue clickable link" feature.

**Comment by space192** [comment]
the app starts now ! And during the lab i've tried to launch vscode server with and without reservation.
it works without any reservation, but doesn't when I have a reservation code !

**Comment by jeremyfix** [comment]
Humm ... there should be no reason to have a difference between "with reservation" and "without reservation";

I just gave a try on Ubuntu . In both cases, running VSCode server works; 

One thing I noticed, is that you may need to wait a bit before being able to contact the vscode server through the ssh tunnel adress indicated by dcejs ; Like 1 or 2 minutes;    Actually, dcejs starts vscode server in background and immediately setup the ssh tunnel ; This implies the ssh tunnel is certainly established before vscode server starts.

Probably the simplest would be to debug that together; I will contact you.

**Comment by JasonMendoza2008** [comment]
FYI The "with reservation" mode works for the students that had problems with the previous versions (same error).

**Comment by jeremyfix** [comment]
Thanks for the feedback , I will release the pre-release  and close the issue;
